### ISSUE TITLE
Breaking because WAPM is unified into Wasmer 

### ISSUE THREAD

**Issue by cedmoh** [hotg-ai/cargo-wapm#2]
# Observed issue

when running `$ cargo wapm` I get

```bash
INFO publish: cargo_wapm::publish: Getting ready to publish dry_run=false pkg="universal_lib "
Error: Unable to publish "universal_lib "

Caused by:
    0: Unable to start "wapm". Is it installed?
    1: No such file or directory (os error 2)
```

it is not possible to install `wapm` anymore as it has been merged into `wasmer` as stated [here](https://wasmer.io/posts/welcome-to-the-new-wasmer).

 # Expected behavior

`cargo-wapm` is able to work with the `wasmer` cli only and does not rely on `wapm` anymore

**Comment by Michael-F-Bryan** [comment]
@SadraMoh this repository is no longer under development because Hammer of the Gods shut down.

I was the owner of the project though, and when I started working for Wasmer we forked the project there. Since then, we've renamed it to `cargo-wasmer` and updated the code to use the `wasmer` CLI.

You can see more in the [`wasmerio/cargo-wasmer`](https://github.com/wasmerio/cargo-wasmer) repo.
